external-dns:
  provider:
    name: cloudflare
  txtOwnerId: homelab-main
  domainFilters:
    - yona.works
  annotationFilter: external-dns.alpha.kubernetes.io/exclude notin (true)
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: value
  interval: 5m
  triggerLoopOnEvent: true
  serviceMonitor:
    enabled: true