cert-manager:
  installCRDs: true
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true

cert-manager-webhook-transip:
  groupName: acme.jonaskoperdraat.nl
  certManager:
    namespace: cert-manager
    serviceAccountName: cert-manager
  transip:
    existingSecret:
      enabled: true
      name: transip-private-key
      apiKeyKey: private-key
      accountNameKey: account-name
