cert-manager:
  installCRDs: true
  prometheus:
    enabled: true
    servicemonitor:
      enabled: true

cert-manager-webhook-transip:
  groupName: acme.jonaskoperdraat.nl
  certManager:
    namespace: cert-manager
    serviceAccountName: cert-manager
  secretName:
    - transip-credentials

transip:
  accountName: jkoper
