nfs-subdir-external-provisioner:
  nfs:
    server: 192.168.88.8
    path: /volume1/backup-home-lab
    mountOptions:
      - nfsvers=4.1
  storageClass:
    name: nas-nfs-backup
    defaultClass: false
    reclaimPolicy: Retain
    archiveOnDelete: true
    accessModes: ReadWriteMany
